# -*- coding: utf-8 -*-
"""ai agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_ewOSVDpR-6msjNatzpcMRkaDlXOQtY
"""

import streamlit as st
from openai import OpenAI

# Use OpenAI client (new in v1+)
client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])

st.set_page_config(page_title="Healthcare Symptom Checker", layout="centered")

st.title("🩺 Healthcare Symptom Checker AI")
st.markdown("Enter your symptoms and get basic suggestions. (For **educational purposes only**)")

user_input = st.text_area("Describe your symptoms here:")

if st.button("Check Now"):
    if not user_input.strip():
        st.warning("Please enter your symptoms before clicking.")
    else:
        with st.spinner("Analyzing your input..."):
            try:
                chat_response = client.chat.completions.create(
                    model="gpt-3.5-turbo",
                    messages=[
                        {"role": "system", "content": "You're a helpful healthcare assistant providing basic, non-diagnostic suggestions. Always remind users to consult a doctor."},
                        {"role": "user", "content": f"My symptoms: {user_input}"}
                    ]
                )
                st.success("Here’s what I found:")
                st.write(chat_response.choices[0].message.content)
            except Exception as e:
                st.error(f"An error occurred: {str(e)}")